/**
 * Loads the compact SATCAT map (public/satcat.json, generated by
 * `npm run fetch-satcat`) once and exposes synchronous lookups by NORAD id.
 * Entry shape: [ownerCode, typeCode]  e.g. ["US","PAY"].
 */
type Entry = [string, string];

let map: Record<string, Entry> | null = null;
let loading: Promise<void> | null = null;

export function loadSatcat(): Promise<void> {
  if (map) return Promise.resolve();
  if (loading) return loading;
  loading = fetch('/satcat.json')
    .then((r) => (r.ok ? r.json() : {}))
    .then((data) => {
      map = data as Record<string, Entry>;
      console.info(`[satcat] loaded ${Object.keys(map).length} catalogue records`);
    })
    .catch((e) => {
      console.warn('[satcat] failed to load /satcat.json — run `npm run fetch-satcat`', e);
      map = {};
    });
  return loading;
}

export function satcatOwner(norad: string): string | undefined {
  return map?.[norad]?.[0];
}

export function satcatType(norad: string): string | undefined {
  return map?.[norad]?.[1];
}

export function satcatReady(): boolean {
  return map !== null;
}
