/**
 * Contract-faithful MOCAT mock data.
 *
 * Produces RawMOCATOutput for the four canonical scenarios, using the
 * published-literature intervention effects from the backend plan
 * (reference-project-code/plans/02_MOCAT_SIMULATION.md → INTERVENTION_EFFECTS).
 *
 * These mocks have the exact shape the live API will return, so the UI built
 * against them is the UI that ships (see plans/06_INTEGRATION_AND_MOCKING.md).
 */

import type { InterventionType, RawMOCATOutput, ScenarioConfig } from './contracts';

// Initial population per altitude shell (illustrative but realistically distributed —
// most mass in the 500–900 km LEO bands).
interface ShellSeed {
  label: string;
  payloads: number;
  debris: number;
  rocketBodies: number;
}

const SHELL_SEEDS: ShellSeed[] = [
  { label: '200-400km', payloads: 400, debris: 300, rocketBodies: 20 },
  { label: '400-500km', payloads: 800, debris: 600, rocketBodies: 40 },
  { label: '500-600km', payloads: 3500, debris: 2500, rocketBodies: 120 },
  { label: '600-700km', payloads: 1200, debris: 1800, rocketBodies: 100 },
  { label: '700-800km', payloads: 900, debris: 2200, rocketBodies: 150 },
  { label: '800-900km', payloads: 700, debris: 2600, rocketBodies: 180 },
  { label: '900-1000km', payloads: 400, debris: 1400, rocketBodies: 90 },
  { label: '1000-1200km', payloads: 500, debris: 1600, rocketBodies: 110 },
  { label: '1200-1500km', payloads: 200, debris: 700, rocketBodies: 60 },
  { label: '1500-2000km', payloads: 150, debris: 500, rocketBodies: 50 },
  { label: '2000-5000km', payloads: 120, debris: 400, rocketBodies: 40 },
];

const INTERVENTION_EFFECTS: Record<InterventionType, { debrisGrowth: number; collisionScale: number }> = {
  baseline: { debrisGrowth: 1.04, collisionScale: 1.0 },
  adr: { debrisGrowth: 0.96, collisionScale: 0.77 },
  launch_cap: { debrisGrowth: 0.98, collisionScale: 0.89 },
  ai_traffic_mgmt: { debrisGrowth: 1.02, collisionScale: 0.82 },
  hybrid: { debrisGrowth: 0.93, collisionScale: 0.69 },
};

export const SCENARIOS: ScenarioConfig[] = [
  {
    scenario_id: 'baseline_2024',
    name: 'Baseline (No Intervention)',
    intervention: 'baseline',
    simulation_years: 30,
    annual_launch_rate: 500,
    adr_rate: 0,
    adr_target_shells: null,
    launch_rate_multiplier: 1.0,
    collision_avoidance_efficiency: 0.0,
  },
  {
    scenario_id: 'adr_aggressive_2024',
    name: 'Active Debris Removal (Aggressive)',
    intervention: 'adr',
    simulation_years: 30,
    annual_launch_rate: 500,
    adr_rate: 50,
    adr_target_shells: [2, 3, 4, 5],
    launch_rate_multiplier: 1.0,
    collision_avoidance_efficiency: 0.0,
  },
  {
    scenario_id: 'launch_cap_2024',
    name: 'Launch Cap (50% Reduction)',
    intervention: 'launch_cap',
    simulation_years: 30,
    annual_launch_rate: 500,
    adr_rate: 0,
    adr_target_shells: null,
    launch_rate_multiplier: 0.5,
    collision_avoidance_efficiency: 0.0,
  },
  {
    scenario_id: 'hybrid_2024',
    name: 'Hybrid (ADR + Cap + AI)',
    intervention: 'hybrid',
    simulation_years: 30,
    annual_launch_rate: 500,
    adr_rate: 30,
    adr_target_shells: [2, 3, 4, 5],
    launch_rate_multiplier: 0.75,
    collision_avoidance_efficiency: 0.35,
  },
];

function buildMockOutput(config: ScenarioConfig): RawMOCATOutput {
  const effects = INTERVENTION_EFFECTS[config.intervention];
  const years = config.simulation_years;
  const nShells = SHELL_SEEDS.length;
  const adrShells = new Set(config.adr_target_shells ?? []);
  const launchMult = config.launch_rate_multiplier;
  const caEff = config.collision_avoidance_efficiency;

  const payloads: number[][] = [];
  const debris: number[][] = [];
  const rockets: number[][] = [];
  const collisions: number[][] = [];

  // Iterative recurrence so ADR (fixed removal/yr) and collision feedback read realistically.
  let prevDebris = SHELL_SEEDS.map((s) => s.debris);
  let prevColl = SHELL_SEEDS.map(() => 0);

  for (let t = 0; t <= years; t++) {
    const dRow: number[] = [];
    const cRow: number[] = [];
    const pRow: number[] = [];
    const rRow: number[] = [];

    for (let s = 0; s < nShells; s++) {
      const seed = SHELL_SEEDS[s];

      let d: number;
      if (t === 0) {
        d = seed.debris;
      } else {
        d = prevDebris[s] * effects.debrisGrowth;
        if (adrShells.has(s)) d -= config.adr_rate;
        // fragments generated by last year's collisions feed back into debris
        d += prevColl[s] * 25 * (1 - caEff);
        d = Math.max(0, d);
      }

      // collisions scale super-linearly with density → congested shells dominate
      const coll = Math.pow(d / 1000, 1.6) * effects.collisionScale;

      const p = seed.payloads * Math.pow(1 + 0.025 * launchMult, t);
      const r = seed.rocketBodies * Math.pow(1 + 0.008 * launchMult, t);

      dRow.push(Math.round(d));
      cRow.push(Number(coll.toFixed(2)));
      pRow.push(Math.round(p));
      rRow.push(Math.round(r));
    }

    payloads.push(pRow);
    debris.push(dRow);
    rockets.push(rRow);
    collisions.push(cRow);
    prevDebris = dRow;
    prevColl = cRow;
  }

  const totalObjects = payloads.map((_, t) =>
    payloads[t].reduce((a, b) => a + b, 0) +
    debris[t].reduce((a, b) => a + b, 0) +
    rockets[t].reduce((a, b) => a + b, 0),
  );
  const totalColl = collisions.map((row) => Number(row.reduce((a, b) => a + b, 0).toFixed(2)));

  return {
    scenario_id: config.scenario_id,
    simulation_years: years,
    shells: SHELL_SEEDS.map((s) => s.label),
    timesteps: Array.from({ length: years + 1 }, (_, i) => i),
    payloads_per_shell: payloads,
    debris_per_shell: debris,
    rocket_bodies_per_shell: rockets,
    collisions_per_shell: collisions,
    total_objects_per_year: totalObjects,
    total_collisions_per_year: totalColl,
    ran_at: new Date().toISOString(),
    runtime_seconds: 0.1,
  };
}

/** Precomputed mock results keyed by scenario_id. */
export const MOCK_RESULTS: Record<string, RawMOCATOutput> = Object.fromEntries(
  SCENARIOS.map((c) => [c.scenario_id, buildMockOutput(c)]),
);
